# Generated by Django 5.0.4 on 2024-04-19 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mysite", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="worker",
            name="worker_groups",
        ),
        migrations.RemoveField(
            model_name="worker",
            name="worker_permissions",
        ),
    ]
